## vim:ft=kitty

## name:     Hollow Knight 2
## author:   zaikko
## license:  MIT
## upstream: 
## blurb:    idk

## The basic colors
foreground              #d0d0d0
background              #000000
selection_foreground    #000000
selection_background    #3c3836

## Cursor colors
cursor                  #d0d0d0
cursor_text_color       #000000

## URL underline color when hovering with mouse
url_color               #7a7a7a

## Kitty window border colors
active_border_color     #7daea3
inactive_border_color   #504945
bell_border_color       #d8a657

## OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

## Tab bar colors
active_tab_foreground   #000000
active_tab_background   #7a7a7a
inactive_tab_foreground #d0d0d0
inactive_tab_background #282828
tab_bar_background      #000000

## Colors for marks (marked text in the terminal)
mark1_foreground        #000000
mark1_background        #7daea3
mark2_foreground        #000000
mark2_background        #d3869b
mark3_foreground        #000000
mark3_background        #89b482

## The 16 terminal colors

## black
color0  #000000
color8  #666666

## red
color1  #b3b3b3
color9  #b3b3b3

## green
color2  #a6a6a6
color10 #a6a6a6

## yellow
color3  #c7c7c7
color11 #c7c7c7

## blue
color4  #7a7a7a
color12 #7a7a7a

## magenta
color5  #9e9e9e
color13 #9e9e9e

## cyan
color6  #8f8f8f
color14 #8f8f8f

## white
color7  #e0e0e0
color15 #e0e0e0
