## vim:ft=kitty

## name:     Hollow Knight 2
## author:   zaikko
## license:  MIT
## upstream: 
## blurb:    idk

## The basic colors
foreground              #d4be98
background              #0c0e0f
selection_foreground    #0c0e0f
selection_background    #3c3836

## Cursor colors
cursor                  #d4be98
cursor_text_color       #0c0e0f

## URL underline color when hovering with mouse
url_color               #d2b79d

## Kitty window border colors
active_border_color     #7daea3
inactive_border_color   #504945
bell_border_color       #d8a657

## OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

## Tab bar colors
active_tab_foreground   #0c0e0f
active_tab_background   #d2b79d
inactive_tab_foreground #d4be98
inactive_tab_background #282828
tab_bar_background      #0c0e0f

## Colors for marks (marked text in the terminal)
mark1_foreground        #0c0e0f
mark1_background        #7daea3
mark2_foreground        #0c0e0f
mark2_background        #d3869b
mark3_foreground        #0c0e0f
mark3_background        #89b482

## The 16 terminal colors

## black
color0  #0c0e0f
color8  #665c54

## red
color1  #ea6962
color9  #ea6962

## green
color2  #733838
color10 #733838

## yellow
color3  #d8a657
color11 #d8a657

## blue
color4  #7daea3
color12 #7daea3

## magenta
color5  #d3869b
color13 #d3869b

## cyan
color6  #733838
color14 #733838

## white
color7  #d4be98
color15 #ddc7a1
